main: me.RockinChaos.itemjoin.ItemJoin
version: 5.0.5-SNAPSHOT-b${env.BUILD_NUMBER}
name: ItemJoin
author: RockinChaos
api-version: 1.13
load: POSTWORLD
description: Get custom items on join.
website: https://www.spigotmc.org/resources/itemjoin.12661/
softdepend: [AuthMe, BetterNick, HeadDatabase, Multiverse-Core, Multiverse-Inventories, MyWorlds, PerWorldInventory, PerWorldPlugins, PlaceholderAPI, TokenEnchant, Vault, WorldGuard, xInventories]
          
permissions:
   itemjoin.*:
      description: Allows use of all commands.
      default: false
      children:
          itemjoin.all: true
   itemjoin.all:
      description: Allows use of all commands.
      default: false
      children:
          itemjoin.permissions: true
          itemjoin.use: true
          itemjoin.reload: true
          itemjoin.menu: true
          itemjoin.creator: true
          itemjoin.updates: true
          itemjoin.autoupdate: true
          itemjoin.purge: true
          itemjoin.save: true
          itemjoin.get: true
          itemjoin.get.others: true
          itemjoin.remove: true
          itemjoin.remove.others: true
          itemjoin.enable: true
          itemjoin.enable.others: true
          itemjoin.disable: true
          itemjoin.disable.others: true
          itemjoin.list: true
          itemjoin.bypass.inventorymodify: false
   itemjoin.permissions:
      description: Allows use of the /itemjoin permissions commands.
      default: true
   itemjoin.use:
      description: Allows use of basic commands.
      default: true
   itemjoin.reload:
      description: Allows use of /itemjoin reload command.
      default: false
   itemjoin.menu:
      description: Allows use of /itemjoin menu command.
      default: false
   itemjoin.creator:
      description: Allows use of /itemjoin menu command.
      default: false
   itemjoin.updates:
      description: Allows use of the /itemjoin updates command.
      default: false
   itemjoin.autoupdate:
      description: Allows use of the /itemjoin autoupdate command.
      default: false
   itemjoin.purge:
      description: Allows use of the /itemjoin purge command.
      default: false
   itemjoin.save:
      description: Allows use of the /itemjoin save <item> command.
      default: false
   itemjoin.get:
      description: Allows use of the /itemjoin get <item> command.
      default: false
   itemjoin.get.others:
      description: Allows use of the /itemjoin get <item> <player> for player command.
      default: false
   itemjoin.remove:
      description: Allows use of the /itemjoin remove <item> command.
      default: false
   itemjoin.remove.others:
      description: Allows use of the /itemjoin remove <item> <player> for player command.
      default: false
   itemjoin.enable:
      description: Allows use of the /itemjoin enable global command.
      default: false
   itemjoin.enable.others:
      description: Allows use of the /itemjoin enable <player> for player command.
      default: false
   itemjoin.disable:
      description: Allows use of the /itemjoin disable global command.
      default: false
   itemjoin.disable.others:
      description: Allows use of the /itemjoin disable <player> for player command.
      default: false
   itemjoin.list:
      description: Allows use of the /itemjoin list command.
      default: false
   itemjoin.bypass.inventorymodify:
      description: Players with this permission will bypass the inventory-modify restrictions.
      default: false
      
commands:
   itemjoin:
      description: Displays a menu giving credit to the creator and the help menu command.
      permission: itemjoin.use
      aliases: [ij]
      usage: |
          /itemjoin
          Example: /itemjoin